CC=gcc
CFLAGS=-c -Wall -lncurses
LDFLAGS= -pthread
SOURCES= main.c iface.c sniffer.c epoll.c epoll.h iface.h sniffer.h 
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=analyzer

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.c.o: 
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm *.o 
